package com.rawr.camera.integration

import com.rawr.camera.BuildConfig
import com.rawr.camera.model.TonemapCatalog
import com.rawr.camera.model.valueFor
import com.rawr.camera.settings.model.MultiframeMergeAlgorithm
import com.rawr.camera.settings.model.SettingsValues
import com.rawr.camera.settings.model.toLegacy
import org.json.JSONObject

/** Portable capture intent. Resolved frame values are added by the native DNG adapter. */
internal object CaptureRecipe {
    fun nativeTone(v: SettingsValues): FloatArray {
        val tone = v.activeImageTone()
        val contract = com.rawr.camera.model.TonemapControlContract
        return floatArrayOf(tone.renderExposure, contract.blackPointNativeFromUi(tone.blacks),
            contract.shadowNativeFromUi(tone.shadows), contract.midtoneNativeFromUi(tone.midtones),
            contract.contrastNativeFromUi(tone.contrast), contract.whitePointNativeFromUi(tone.whites),
            contract.highlightNativeFromUi(tone.highlights), tone.saturation, tone.vibrance,
            v.photoHighlightMethod.toFloat(), v.photoHighlightThreshold, v.photoHighlightCompression)
    }

    fun freezeAssets(context: android.content.Context, v: SettingsValues): SettingsValues {
        val profile = v.userLutProfiles.firstOrNull { it.id == v.selectedUserLutProfileId } ?: return v
        val frozen = com.rawr.camera.settings.preferences.LutProfileFileStore(context).freezeForCapture(profile)
        return v.copy(selectedUserLutProfileId = frozen.id, userLutProfiles = v.userLutProfiles + frozen)
    }

    fun encode(v: SettingsValues, filesDir: java.io.File? = null): String = JSONObject().apply {
        put("schema", "com.rawrcam.processing-recipe")
        put("version", 1)
        put("applicationVersion", BuildConfig.VERSION_NAME)
        put("pipelineVersion", "rawr-still-1")
        put("importedProfileId", v.selectedUserLutProfileId ?: JSONObject.NULL)
        v.userLutProfiles.firstOrNull { it.id == v.selectedUserLutProfileId }?.let { profile ->
            put("importedProfile", JSONObject().apply {
                put("id", profile.id)
                put("name", profile.name)
                put("inputGamut", profile.inputGamut.name)
                put("inputTransfer", profile.inputTransfer.name)
                put("outputGamut", profile.outputGamut.name)
                put("outputTransfer", profile.outputTransfer.name)
                put("afterLut", profile.afterLut.name)
                put("stages", org.json.JSONArray().apply {
                    profile.stages.forEach { stage -> put(JSONObject().apply {
                        put("name", stage.fileName)
                        put("relativePath", stage.relativePath)
                        if (filesDir != null) {
                            val digest = java.security.MessageDigest.getInstance("SHA-256")
                            java.io.File(filesDir, stage.relativePath).inputStream().use { input ->
                                val buffer = ByteArray(65536)
                                while (true) { val count = input.read(buffer); if (count < 0) break; digest.update(buffer, 0, count) }
                            }
                            put("sha256", digest.digest().joinToString("") { "%02x".format(it) })
                        }
                    }) }
                })
            })
        }
        put("demosaicAlgorithm", v.demosaicAlgorithm.name)
        put("dualAutoContrast", v.dualAutoContrast)
        put("dualContrastPercent", v.dualContrastPercent)
        put("quadfixEnabled", v.quadfixEnabled)
        put("quadfixFastMedian", v.quadfixFastMedian)
        put("fccSteps", v.photoFccSteps)
        put("lensShadingCorrectionEnabled", v.photoLensShadingEnabled)
        put("highlightReconstructionEnabled", v.photoHighlightEnabled)
        put("highlightReconstructionMethod", v.photoHighlightMethod)
        put("highlightThreshold", v.photoHighlightThreshold)
        put("highlightCompression", v.photoHighlightCompression)
        put("ultraHdrEnabled", v.ultraHdrEnabled)
        put("distortionCorrectionEnabled", v.distortionCorrectionEnabled)
        put("defringeEnabled", v.photoDefringeEnabled)
        put("defringeStrength", v.photoDefringeStrength)
        put("defringeEdgeThreshold", v.photoDefringeEdgeThreshold)
        put("defringeLumaFloor", v.photoDefringeLumaFloor)
        // Photo denoise writes the stable recipe keys from the sealed value.
        val legacyDenoise = v.photoDenoise.toLegacy()
        put("denoiseEnabled", legacyDenoise.enabled)
        put("denoiseStrength", legacyDenoise.waveletStrength)
        put("denoiseDetail", legacyDenoise.waveletDetail)
        put("denoiseLuma", legacyDenoise.waveletLuma)
        put("denoiseScales", legacyDenoise.waveletScales)
        put("denoiseMethod", legacyDenoise.method)
        put("galoshRawMode", legacyDenoise.rawMode)
        put("galoshStrength", legacyDenoise.rawStrength)
        put("galoshLuma", legacyDenoise.rawLuma)
        put("galoshChroma", legacyDenoise.rawChroma)
        put("galoshYuvMode", legacyDenoise.yuvMode)
        put("galoshYuvStrengthY", legacyDenoise.yuvStrengthY)
        put("galoshYuvStrengthC", legacyDenoise.yuvStrengthC)
        put("filmSimEnabled", v.filmSimEnabled)
        put("colorRenderProfile", v.colorRenderProfile.name)
        put("multiframeBaseFrameMode", v.multiframeBaseFrameMode.name)
        put("tone", JSONObject().apply {
            val value = v.activeImageTone()
            TonemapCatalog.all.forEach { put(it.jsonKey, value.valueFor(it)) }
            put("colorRenderingStrength", value.colorRenderingStrength)
            put("wbTemperature", value.wbTemperature)
            put("wbTint", value.wbTint)
            put("outputColorSpaceId", value.outputColorSpaceId)
            put("transferFunctionId", value.transferFunctionId)
            put("jpegQuality", value.jpegQuality)
            put("jpegChromaSubsamplingId", value.jpegChromaSubsamplingId)
        })
        put("film", JSONObject().apply {
            val value = v.filmSimLook
            put("film", value.film)
            put("paper", value.paper)
            put("inputColorSpace", value.inputColorSpace)
            put("outputColorSpace", value.outputColorSpace)
            put("rgbToRawMethod", value.rgbToRawMethod)
            put("process", value.process)
            put("scanNegativeInvert", value.scanNegativeInvert)
            put("filmPushPullMode", value.filmPushPullMode)
            put("printerLightsGang", value.printerLightsGang)
            put("printerLightCalibration", value.printerLightCalibration)
            put("grainEnabled", value.grainEnabled)
            put("grainModel", value.grainModel)
            put("filmFormat", value.filmFormat)
            put("grainSublayersEnabled", value.grainSublayersEnabled)
            put("grainSubLayerCount", value.grainSubLayerCount)
            put("grainSeed", value.grainSeed)
            put("grainAnimate", value.grainAnimate)
            put("cameraUvFilterEnabled", value.cameraUvFilterEnabled)
            put("cameraIrFilterEnabled", value.cameraIrFilterEnabled)
            put("filmExposureEv", value.filmExposureEv)
            put("printExposureEv", value.printExposureEv)
            put("filmPushPullStops", value.filmPushPullStops)
            put("filmGamma", value.filmGamma)
            put("printPushPullStops", value.printPushPullStops)
            put("printGamma", value.printGamma)
            put("printShadowShape", value.printShadowShape)
            put("printHighlightShape", value.printHighlightShape)
            put("negativeBleachBypassAmount", value.negativeBleachBypassAmount)
            put("negativeLeucoCyanCoupling", value.negativeLeucoCyanCoupling)
            put("printBleachBypassAmount", value.printBleachBypassAmount)
            put("preflashExposure", value.preflashExposure)
            put("preflashMFilterShift", value.preflashMFilterShift)
            put("preflashYFilterShift", value.preflashYFilterShift)
            put("filterC", value.filterC)
            put("filterMShift", value.filterMShift)
            put("filterYShift", value.filterYShift)
            put("printerLightsR", value.printerLightsR)
            put("printerLightsG", value.printerLightsG)
            put("printerLightsB", value.printerLightsB)
            put("enlargerScale", value.enlargerScale)
            put("enlargerOffsetXPercent", value.enlargerOffsetXPercent)
            put("enlargerOffsetYPercent", value.enlargerOffsetYPercent)
            put("grainAmount", value.grainAmount)
            put("grainSaturation", value.grainSaturation)
            put("grainParticleAreaUm2", value.grainParticleAreaUm2)
            put("grainParticleScaleR", value.grainParticleScaleR)
            put("grainParticleScaleG", value.grainParticleScaleG)
            put("grainParticleScaleB", value.grainParticleScaleB)
            put("grainParticleScaleLayer0", value.grainParticleScaleLayer0)
            put("grainParticleScaleLayer1", value.grainParticleScaleLayer1)
            put("grainParticleScaleLayer2", value.grainParticleScaleLayer2)
            put("grainDensityMinR", value.grainDensityMinR)
            put("grainDensityMinG", value.grainDensityMinG)
            put("grainDensityMinB", value.grainDensityMinB)
            put("grainUniformityR", value.grainUniformityR)
            put("grainUniformityG", value.grainUniformityG)
            put("grainUniformityB", value.grainUniformityB)
            put("grainFinalBlurUm", value.grainFinalBlurUm)
            put("grainBlurDyeCloudsUm", value.grainBlurDyeCloudsUm)
            put("grainMicroStructureScale", value.grainMicroStructureScale)
            put("grainMicroStructureSigmaNm", value.grainMicroStructureSigmaNm)
            put("cameraUvCutNm", value.cameraUvCutNm)
            put("cameraIrCutNm", value.cameraIrCutNm)
            put("dirCouplersAmount", value.dirCouplersAmount.coerceIn(0f, 1f))
            put("dirCouplersDiffusionUm", value.dirCouplersDiffusionUm)
            put("dirCouplersDiffusionTailUm", value.dirCouplersDiffusionTailUm)
            put("dirCouplersDiffusionTailWeight", value.dirCouplersDiffusionTailWeight)
            put("dirCouplersInhibitionSameLayer", value.dirCouplersInhibitionSameLayer)
            put("dirCouplersInhibitionInterlayer", value.dirCouplersInhibitionInterlayer)
            put("dirCouplersGammaSameLayerR", value.dirCouplersGammaSameLayerR)
            put("dirCouplersGammaSameLayerG", value.dirCouplersGammaSameLayerG)
            put("dirCouplersGammaSameLayerB", value.dirCouplersGammaSameLayerB)
            put("dirCouplersGammaRToG", value.dirCouplersGammaRToG)
            put("dirCouplersGammaRToB", value.dirCouplersGammaRToB)
            put("dirCouplersGammaGToR", value.dirCouplersGammaGToR)
            put("dirCouplersGammaGToB", value.dirCouplersGammaGToB)
            put("dirCouplersGammaBToR", value.dirCouplersGammaBToR)
            put("dirCouplersGammaBToG", value.dirCouplersGammaBToG)
            put("scannerEnabled", value.scannerEnabled)
            put("scannerWhiteCorrection", value.scannerWhiteCorrection)
            put("scannerBlackCorrection", value.scannerBlackCorrection)
            put("scannerWhiteLevel", value.scannerWhiteLevel)
            put("scannerBlackLevel", value.scannerBlackLevel)
            put("glarePercent", value.glarePercent)
            put("glareRoughness", value.glareRoughness)
            put("glareBlur", value.glareBlur)
            put("scannerMtf50LpMm", value.scannerMtf50LpMm)
            put("scannerUnsharpRadiusUm", value.scannerUnsharpRadiusUm)
            put("scannerUnsharpAmount", value.scannerUnsharpAmount)
            put("halationEnabled", value.halationEnabled)
            put("scatterAmount", value.scatterAmount)
            put("scatterScale", value.scatterScale)
            put("halationAmount", value.halationAmount)
            put("halationScale", value.halationScale)
            put("halationStrengthR", value.halationStrengthR)
            put("halationStrengthG", value.halationStrengthG)
            put("halationStrengthB", value.halationStrengthB)
            put("halationFirstSigmaUmR", value.halationFirstSigmaUmR)
            put("halationFirstSigmaUmG", value.halationFirstSigmaUmG)
            put("halationFirstSigmaUmB", value.halationFirstSigmaUmB)
            put("halationBoostEv", value.halationBoostEv)
            put("halationBoostRange", value.halationBoostRange)
            put("halationProtectEv", value.halationProtectEv)
            put("cameraDiffusionEnabled", value.cameraDiffusionEnabled)
            put("cameraDiffusionFamily", value.cameraDiffusionFamily)
            put("cameraDiffusionStrength", value.cameraDiffusionStrength)
            put("cameraDiffusionSpatialScale", value.cameraDiffusionSpatialScale)
            put("cameraDiffusionHaloWarmth", value.cameraDiffusionHaloWarmth)
            put("cameraDiffusionCoreIntensity", value.cameraDiffusionCoreIntensity)
            put("cameraDiffusionCoreSize", value.cameraDiffusionCoreSize)
            put("cameraDiffusionHaloIntensity", value.cameraDiffusionHaloIntensity)
            put("cameraDiffusionHaloSize", value.cameraDiffusionHaloSize)
            put("cameraDiffusionBloomIntensity", value.cameraDiffusionBloomIntensity)
            put("cameraDiffusionBloomSize", value.cameraDiffusionBloomSize)
            put("printDiffusionEnabled", value.printDiffusionEnabled)
            put("printDiffusionFamily", value.printDiffusionFamily)
            put("printDiffusionStrength", value.printDiffusionStrength)
            put("printDiffusionSpatialScale", value.printDiffusionSpatialScale)
            put("printDiffusionHaloWarmth", value.printDiffusionHaloWarmth)
            put("printDiffusionCoreIntensity", value.printDiffusionCoreIntensity)
            put("printDiffusionCoreSize", value.printDiffusionCoreSize)
            put("printDiffusionHaloIntensity", value.printDiffusionHaloIntensity)
            put("printDiffusionHaloSize", value.printDiffusionHaloSize)
            put("printDiffusionBloomIntensity", value.printDiffusionBloomIntensity)
            put("printDiffusionBloomSize", value.printDiffusionBloomSize)
        })
        put("multiframe", JSONObject().apply {
            val value = v.multiframeTuning.sanitized()
            put("mergeAlgorithm", value.mergeAlgorithm.name)
            put("hdrPlusStrength", value.hdrPlusStrength)
            put("hdrPlusTileSize", value.hdrPlusTileSize)
            if (value.mergeAlgorithm == MultiframeMergeAlgorithm.HdrPlusBracketed) {
                put("bracketEv", value.bracketEv)
                put("bracketFrames", value.bracketFrames)
            }
            put("maxFrames", value.maxFrames)
            put("lkIterations", value.lkIterations)
            put("hessianEpsilonExponent", value.hessianEpsilonExponent)
            put("kDetail", value.kDetail)
            put("kDenoise", value.kDenoise)
            put("dThreshold", value.dThreshold)
            put("dTransition", value.dTransition)
            put("kStretch", value.kStretch)
            put("kShrink", value.kShrink)
            put("robustnessT", value.robustnessT)
            put("robustnessS1", value.robustnessS1)
            put("robustnessS2", value.robustnessS2)
            put("motionThreshold", value.motionThreshold)
            put("flatSigma", value.flatSigma)
            put("detailFloorSigma", value.detailFloorSigma)
            put("scaleBandwidthGain", value.scaleBandwidthGain)
            put("coverageNeffLo", value.coverageNeffLo)
            put("coverageNeffHi", value.coverageNeffHi)
            put("coverageMassLo", value.coverageMassLo)
            put("coverageMassHi", value.coverageMassHi)
            put("fallbackChroma", value.fallbackChroma)
            put("fallbackLuma", value.fallbackLuma)
        })
    }.toString()
}
